{application,csv,
             [{applications,[kernel,stdlib,elixir,parallel_stream]},
              {description,"CSV Decoding and Encoding for Elixir"},
              {modules,['Elixir.CSV','Elixir.CSV.Decoder',
                        'Elixir.CSV.Decoder.RowLengthError',
                        'Elixir.CSV.Defaults','Elixir.CSV.Encode',
                        'Elixir.CSV.Encode.Any','Elixir.CSV.Encode.BitString',
                        'Elixir.CSV.Encoder','Elixir.CSV.Lexer',
                        'Elixir.CSV.Lexer.EncodingError',
                        'Elixir.CSV.LineAggregator',
                        'Elixir.CSV.LineAggregator.CorruptStreamError',
                        'Elixir.CSV.Parser','Elixir.CSV.Parser.SyntaxError']},
              {registered,[]},
              {vsn,"1.4.3"}]}.
